name: Update EPG

on:
  schedule:
    - cron: "0 */12 * * *"   # roda a cada 12 horas
  workflow_dispatch:          # permite rodar manualmente

jobs:
  update-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install requests pytz

      - name: Run EPG generator
        run: |
          python guia/programacao.py

      - name: Push changes
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "actions-user"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
          git add mylist.xml
          git commit -m "Update EPG data" || echo "No changes"
          git push

